language: rust

env:
  global:
    - secure: "HV2OLxpmvJ5dTaUbtF6advHm2oMovOzvTZd5ghreFzub6Gy8hmmOO4LTytSTL3VwssYHbiPBYjXFnnN1V32yvEzEN+OQoWOJunCFPSw/DNG9i1OMLIYdxwyW72oMi2iKmduKXkrP6OliEomTyfWn2OK5buVo4CK7xASKOqPccFI="

script:
    - cargo build --verbose
    - cargo test --verbose

after_success: |
    [ $TRAVIS_BRANCH = master ] &&
    [ $TRAVIS_PULL_REQUEST = false ] &&
    cargo doc &&
    echo '<meta http-equiv=refresh content=0;url=bmp/index.html>' > target/doc/index.html &&
    sudo pip install ghp-import &&
    ghp-import -n target/doc &&
    git push -fq https://${GH_TOKEN}:x-oauth-basic@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
