[package]

name = "bmp"
version = "0.0.7"
authors = ["Sondre Lefsaker"]

description = "Small library for reading and writing BMP images in Rust"
repository = "https://github.com/sondrele/rust-bmp"

readme = "README.md"

keywords = ["bmp", "image"]

license = "MIT"
